<template>
    <SitePageLayout
        eyebrow="NEWS"
        title="소식"
        description="선교단 소식과 공지"
        :pending="pending"
        :error="error"
    >
        <div class="bmc-grid bmc-grid--2">
            <NuxtLink
                v-for="item in news"
                :key="item.slug || item.id"
                class="bmc-news-card"
                :to="item.link || `/news/${item.slug}`"
                style="text-decoration:none;color:inherit;"
            >
                <p style="margin:0;font-size:0.8125rem;font-weight:700;color:#1e56c8;">{{ item.date }}</p>
                <span v-if="item.autoGenerated" class="bmc-news-card__badge">경기 기록</span>
                <h3 style="margin:0;font-size:1rem;font-weight:800;">{{ item.title }}</h3>
                <p style="margin:0;color:#6b7280;line-height:1.55;">{{ item.summary }}</p>
                <a
                    v-if="item.youtube?.youtubeUrl"
                    class="bmc-inline-link"
                    :href="item.youtube.youtubeUrl"
                    target="_blank"
                    rel="noopener noreferrer"
                    @click.stop
                >
                    경기 영상 보기
                </a>
            </NuxtLink>
        </div>
    </SitePageLayout>
</template>

<script setup lang="ts">
type NewsItem = {
    id?: string;
    slug?: string;
    title: string;
    date: string;
    summary: string;
    link?: string;
    autoGenerated?: boolean;
    youtube?: { youtubeUrl: string };
};

definePageMeta({ title: '소식' });

const { fetchJson } = useBasePath();
const news = ref<NewsItem[]>([]);
const pending = ref(true);
const error = ref('');

function getDateTime(item: NewsItem) {
    const time = new Date(`${item.date}T00:00:00+09:00`).getTime();
    return Number.isFinite(time) ? time : 0;
}

function sortNewsByDateDesc(items: NewsItem[]) {
    return items
        .map((item, index) => ({ item, index }))
        .sort((a, b) => {
            const dateDiff = getDateTime(b.item) - getDateTime(a.item);
            return dateDiff || a.index - b.index;
        })
        .map(({ item }) => item);
}

onMounted(async () => {
    try {
        const [manualNews, generatedNews] = await Promise.all([
            fetchJson<NewsItem[]>('meta/news.json'),
            fetchJson<NewsItem[]>('generated/news.json').catch(() => []),
        ]);
        news.value = sortNewsByDateDesc([...generatedNews, ...manualNews]);
    } catch (err) {
        error.value = err instanceof Error ? err.message : '소식 데이터를 불러오지 못했습니다.';
    } finally {
        pending.value = false;
    }
});
</script>

<style scoped lang="scss">
.bmc-news-card__badge,
.bmc-inline-link {
    font-size: 0.8125rem;
    font-weight: 800;
    color: #1e56c8;
}
</style>
